### PR TITLE
Changes for Big Sur.

### PR DESCRIPTION
**Pull request by brandonplank**
And I compiled everything by default, as I had no problem using yours. It took forever for me to get it working as the build.sh did not want to work for most things.

### CODE REVIEW

**Comment by arch-dev** [comment]
So this changes you have made make  Big Sur running successfully on our laptop? Have you made changes to any bios files or you kept the ones provided by me? Also I noticed you have removed the ssdt patching part in the guide. (I have written it since I didn't know if everyone following this guide would had my same bios version, but if you can confirm that ssdt changes among bios versions are the same, great we can  remove it).
Also what didn't work with build.sh?
Thank you for you work and tests on new Mac OS version. I will merge you pull request soon and if you want I can add you as collaborator.

**Comment by brandonplank** [comment]
Yeah, so everything in the repo works on our computers.

Took me a while to make sure everything worked.
I just went ahead and compiled all the .dsl files because with the program that you was using to compile, it was failing with syntax errors, but I found a way to compile them with no issue. Everything works as intended! Audio, gpu, everything.

**Comment by brandonplank** [comment]
You can also update from Catilina to Big Sur as long as you have open core v0.6.2 and the SecureBootModel disabled(new in clover 0.6.2)

**Comment by brandonplank** [comment]
I can confirm as I updated to the latest beta., new working wifi drivers for usb wifi adapters are here: https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter

Disable sip by adding this to the nvram, then reseting it next boot:
```
<key>csr-active-config</key>
<data>/w8AAA==</data> <- FF0F0000 if using Clover config / Opencore config
```

**Comment by arch-dev** [comment]
So nice to hear that. Thank you again for you work and tests 👍

**Comment by brandonplank** [comment]
Haha, I’m probably going to make a section dedicated to macOS itself sense your intrusions are jumbled together.

If I make a Mac section, would you make a windows section?

**Comment by arch-dev** [comment]
> Haha, I’m probably going to make a section dedicated to macOS itself sense your intrusions are jumbled together.
> 
> If I make a Mac section, would you make a windows section?

Yes of course

**Pull request merged**
